services:
  - type: web
    name: auto-escrow-bot
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm run server & npm run bot
    envVars:
      - key: DATABASE_URL
        sync: false 
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false 
      - key: ALLOWED_TELEGRAM_USER_ID
        sync: false 
